apiVersion: v1
kind: Secret
metadata:
  name: baby-cry-analyzer-secrets
  namespace: baby-cry-analyzer
  labels:
    app: baby-cry-analyzer
    environment: ${ENV}
    managed-by: terraform
    security-tier: high
  annotations:
    encryption.kubernetes.io/encryption-provider: aes-256
    rotation-schedule: 90d
    last-rotated: timestamp
    audit-log-enabled: "true"
type: Opaque
data:
  # Database Credentials
  # Required for MongoDB Atlas connection with high availability
  DATABASE_URL: ${base64_encoded_mongodb_connection_string}
  DATABASE_NAME: ${base64_encoded_database_name}

  # JWT Authentication
  # Required for secure user session management with 90-day rotation
  JWT_SECRET: ${base64_encoded_jwt_secret}
  JWT_EXPIRATION: ${base64_encoded_jwt_expiration}
  REFRESH_TOKEN_EXPIRATION: ${base64_encoded_refresh_token_expiration}

  # Auth0 Configuration
  # Required for OAuth2/OIDC authentication integration
  AUTH0_DOMAIN: ${base64_encoded_auth0_domain}
  AUTH0_CLIENT_ID: ${base64_encoded_auth0_client_id}
  AUTH0_CLIENT_SECRET: ${base64_encoded_auth0_client_secret}

  # AWS Credentials
  # Required for S3 audio storage and KMS encryption
  AWS_ACCESS_KEY_ID: ${base64_encoded_aws_access_key}
  AWS_SECRET_ACCESS_KEY: ${base64_encoded_aws_secret_key}
  AWS_REGION: ${base64_encoded_aws_region}
  S3_BUCKET_NAME: ${base64_encoded_s3_bucket_name}

  # Redis Cache Configuration
  # Required for session and analysis result caching
  REDIS_URL: ${base64_encoded_redis_connection_string}

  # API Security
  # Required for service-to-service communication
  API_KEY: ${base64_encoded_api_key}

  # Data Encryption
  # Required for AES-256 encryption of sensitive data
  ENCRYPTION_KEY: ${base64_encoded_encryption_key}

---
# RBAC Role for Secret Access
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: secret-reader
  namespace: baby-cry-analyzer
rules:
- apiGroups: [""]
  resources: ["secrets"]
  resourceNames: ["baby-cry-analyzer-secrets"]
  verbs: ["get"]

---
# RBAC Role Binding for Backend Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: backend-secret-reader
  namespace: baby-cry-analyzer
subjects:
- kind: ServiceAccount
  name: backend-sa
  namespace: baby-cry-analyzer
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io

---
# RBAC Role Binding for ML Service Account
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ml-service-secret-reader
  namespace: baby-cry-analyzer
subjects:
- kind: ServiceAccount
  name: ml-service-sa
  namespace: baby-cry-analyzer
roleRef:
  kind: Role
  name: secret-reader
  apiGroup: rbac.authorization.k8s.io