# SwiftLint configuration for Baby Cry Analyzer iOS app
# Version: 0.50.3
# Focus: Code quality, security, and audio processing standards

disabled_rules:
  - trailing_whitespace
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Line length configuration
line_length:
  warning: 120
  error: 150
  ignores_comments: true
  ignores_urls: true

# Function body length
function_body_length:
  warning: 50
  error: 100

# Function parameter count
function_parameter_count:
  warning: 6
  error: 8

# Type body length
type_body_length:
  warning: 300
  error: 500

# File length
file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

# Cyclomatic complexity
cyclomatic_complexity:
  warning: 10
  error: 20

# Nesting configuration
nesting:
  type_level:
    warning: 2
    error: 3

# Identifier naming rules
identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 60
  excluded:
    - id
    - URL
    - x
    - y

# Included/Excluded paths
included:
  - src/ios/BabyCryAnalyzer

excluded:
  - src/ios/Pods
  - src/ios/fastlane
  - src/ios/BabyCryAnalyzer.xcodeproj
  - src/ios/BabyCryAnalyzer.xcworkspace

# Reporter type
reporter: xcode

# Custom rules for Baby Cry Analyzer specific requirements
custom_rules:
  audio_processor_delegate:
    name: "Audio Processor Delegate"
    regex: 'class.*AudioProcessor.*:.*(?!.*AudioProcessorDelegate)'
    message: "AudioProcessor must conform to AudioProcessorDelegate"
    severity: error

  secure_random:
    name: "Secure Random Generation"
    regex: 'arc4random|rand|random'
    message: "Use SecRandomCopyBytes for cryptographic operations"
    severity: error

  encryption_key_size:
    name: "Encryption Key Size"
    regex: 'AES.*key.*length.*(?!32)'
    message: "AES-256 requires 32-byte keys"
    severity: error

  audio_buffer_validation:
    name: "Audio Buffer Validation"
    regex: 'processAudioBuffer.*(?!.*validate)'
    message: "Audio buffer processing must include validation"
    severity: error

  secure_data_storage:
    name: "Secure Data Storage"
    regex: 'UserDefaults\.standard|NSUserDefaults'
    message: "Use KeychainAccess for sensitive data storage"
    severity: error