platform :ios, '14.0'
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

use_frameworks!
install! 'cocoapods', :deterministic_uuids => true

target 'BabyCryAnalyzer' do
  config = use_native_modules!
  use_react_native!(
    :path => config[:reactNativePath],
    :hermes_enabled => true,
    :fabric_enabled => true
  )

  pod 'React-Core', '0.71.0'
  pod 'TensorFlowLiteSwift', '2.12.0'
  pod 'AudioKit', '5.5.8'
  pod 'KeychainAccess', '4.2.2'
  
  pod 'Firebase/Core', '10.12.0'
  pod 'Firebase/Messaging', '10.12.0'
  
  pod 'SwiftLint', '0.51.0', :configurations => ['Debug']

  target 'BabyCryAnalyzerTests' do
    inherit! :complete
  end

  post_install do |installer|
    react_native_post_install(installer)
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        config.build_settings['ENABLE_BITCODE'] = 'NO'
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
    end
  end

  debug_configuration do
    use_flipper!()
  end

  release_configuration do
    use_flipper!(false)
  end
end